---
title: Vasyl Khrystiuk
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: blog/:year/:month/:day/:title.html
    layout: post
    comments: true
markdown: kramdown
kramdown:
  entity_output: :as_input
  parse_block_html: true
theme: jekyll-theme-primer
google_analytics: UA-194224445-1
repository: msangel/msangel.github.io
keep_files:
- CNAME
github:
- metadata
plugins:
  - jekyll-toc
highlighter: rouge
includes_dir: _layouts
