---
title: msangel
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
markdown: kramdown
kramdown:
  entity_output: :as_input
google_analytics: "UA-194224445-1"
