# take a look here: https://github.com/jekyll/github-metadata/blob/8906f2b9c890f0aafef96423c7cd7e5047f7dae4/lib/jekyll-github-metadata/client.rb#L96-L97
# and here: https://jekyllrb.com/docs/continuous-integration/github-actions/

name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
    # https://github.com/marketplace/actions/jekyll-actions
      - uses: actions/checkout@v2
      - uses: helaili/jekyll-action@v2
        with:
          token: ${{ secrets.JEKYLL_GITHUB_TOKEN }}
